# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be77157678e2380e0d0b2dedb36bb18357080118f12e3e25fa37d3d1c68bd2267f68da02ed0da6b4ace1439734008ad5c4361223fb6b538a7cb1496026b4b854

test:
  secret_key_base: d8771ccb6cdb66ae4da940c3b962e6d033543609a368d660aaea8fc6db2d76187dbe53214446bb8baedfe52b2ef42cb9bbb41b5e4a0e03cf814d0763f41d34bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
